openapi: 3.0.3
info:
  title: FuseML core API
  description: Provides an API for the core operations of FuseML
  version: "1.0"
servers:
- url: http://localhost:8000
  description: fuseml-core hosts the core services
paths:
  /api/openapi.json:
    get:
      tags:
      - openapi
      summary: Download gen/http/openapi.json
      description: JSON document containing the API swagger definition
      operationId: openapi#/api/openapi.json
      responses:
        "200":
          description: File downloaded
  /api/openapi.yaml:
    get:
      tags:
      - openapi
      summary: Download gen/http/openapi.yaml
      description: JSON document containing the API swagger definition
      operationId: openapi#/api/openapi.yaml
      responses:
        "200":
          description: File downloaded
  /api/openapi3.json:
    get:
      tags:
      - openapi
      summary: Download gen/http/openapi3.json
      description: JSON document containing the API swagger definition
      operationId: openapi#/api/openapi3.json
      responses:
        "200":
          description: File downloaded
  /api/openapi3.yaml:
    get:
      tags:
      - openapi
      summary: Download gen/http/openapi3.yaml
      description: JSON document containing the API swagger definition
      operationId: openapi#/api/openapi3.yaml
      responses:
        "200":
          description: File downloaded
  /codesets:
    get:
      tags:
      - codeset
      summary: list codeset
      description: Retrieve information about Codesets registered in FuseML.
      operationId: codeset#list
      parameters:
      - name: project
        in: query
        description: List only Codesets that belong to given project
        allowEmptyValue: true
        schema:
          type: string
          description: List only Codesets that belong to given project
          example: mlflow-project-01
        example: mlflow-project-01
      - name: label
        in: query
        description: List only Codesets with matching label
        allowEmptyValue: true
        schema:
          type: string
          description: List only Codesets with matching label
          example: mlflow
        example: mlflow
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Codeset'
                description: Return all registered Codesets matching the query.
                example:
                - description: My first MLFlow application with FuseML
                  label: mlflow
                  location: work/ml/mlflow-code
                  name: mlflow-app-01
                  project: mlflow-project-01
                - description: My first MLFlow application with FuseML
                  label: mlflow
                  location: work/ml/mlflow-code
                  name: mlflow-app-01
                  project: mlflow-project-01
              example:
              - description: My first MLFlow application with FuseML
                label: mlflow
                location: work/ml/mlflow-code
                name: mlflow-app-01
                project: mlflow-project-01
              - description: My first MLFlow application with FuseML
                label: mlflow
                location: work/ml/mlflow-code
                name: mlflow-app-01
                project: mlflow-project-01
        "404":
          description: Not Found response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
    post:
      tags:
      - codeset
      summary: register codeset
      description: Register a Codeset with the FuseML codeset store.
      operationId: codeset#register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Codeset'
            example:
              description: My first MLFlow application with FuseML
              label: mlflow
              location: work/ml/mlflow-code
              name: mlflow-app-01
              project: mlflow-project-01
      responses:
        "201":
          description: Created response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Codeset'
              example:
                description: My first MLFlow application with FuseML
                label: mlflow
                location: work/ml/mlflow-code
                name: mlflow-app-01
                project: mlflow-project-01
        "400":
          description: Bad Request response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /codesets/{project}/{name}:
    get:
      tags:
      - codeset
      summary: get codeset
      description: Retrieve an Codeset from FuseML.
      operationId: codeset#get
      parameters:
      - name: project
        in: path
        description: Project name
        required: true
        schema:
          type: string
          description: Project name
          example: mlflow-project-01
        example: mlflow-project-01
      - name: name
        in: path
        description: Codeset name
        required: true
        schema:
          type: string
          description: Codeset name
          example: mlflow-app-01
        example: mlflow-app-01
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Codeset'
              example:
                description: My first MLFlow application with FuseML
                label: mlflow
                location: work/ml/mlflow-code
                name: mlflow-app-01
                project: mlflow-project-01
        "400":
          description: Bad Request response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "404":
          description: Not Found response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /runnables:
    get:
      tags:
      - runnable
      summary: list runnable
      description: Retrieve information about runnables registered in FuseML.
      operationId: runnable#list
      parameters:
      - name: kind
        in: query
        description: Kind of a registered runnables
        allowEmptyValue: true
        schema:
          type: string
          description: Kind of a registered runnables
          example: builder
        example: builder
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Runnable'
                description: Return all registered runnables matching the query.
                example:
                - created: "2021-04-09T06:17:25Z"
                  id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
                  image:
                    registryUrl: myregistry.io
                    repository: example/builder
                    tag: "1.0"
                  inputs:
                  - kind: parameter
                    name: Input1
                    parameter:
                      datatype: file
                      default: mydata.csv
                      optional: true
                    runnable:
                      kind: builder
                      labels:
                      - label1
                      - label2
                      name: BuilderRun1
                  - kind: parameter
                    name: Input1
                    parameter:
                      datatype: file
                      default: mydata.csv
                      optional: true
                    runnable:
                      kind: builder
                      labels:
                      - label1
                      - label2
                      name: BuilderRun1
                  - kind: parameter
                    name: Input1
                    parameter:
                      datatype: file
                      default: mydata.csv
                      optional: true
                    runnable:
                      kind: builder
                      labels:
                      - label1
                      - label2
                      name: BuilderRun1
                  kind: trainer
                  labels:
                  - trainer
                  name: MyTrainer
                  outputs:
                  - kind: model
                    metadata:
                      datatype: file
                      default: mydata.csv
                      optional: true
                    name: Output1
                    runnable:
                      kind: builder
                      labels:
                      - label1
                      - label2
                      name: BuilderRun1
                  - kind: model
                    metadata:
                      datatype: file
                      default: mydata.csv
                      optional: true
                    name: Output1
                    runnable:
                      kind: builder
                      labels:
                      - label1
                      - label2
                      name: BuilderRun1
                  - kind: model
                    metadata:
                      datatype: file
                      default: mydata.csv
                      optional: true
                    name: Output1
                    runnable:
                      kind: builder
                      labels:
                      - label1
                      - label2
                      name: BuilderRun1
                - created: "2021-04-09T06:17:25Z"
                  id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
                  image:
                    registryUrl: myregistry.io
                    repository: example/builder
                    tag: "1.0"
                  inputs:
                  - kind: parameter
                    name: Input1
                    parameter:
                      datatype: file
                      default: mydata.csv
                      optional: true
                    runnable:
                      kind: builder
                      labels:
                      - label1
                      - label2
                      name: BuilderRun1
                  - kind: parameter
                    name: Input1
                    parameter:
                      datatype: file
                      default: mydata.csv
                      optional: true
                    runnable:
                      kind: builder
                      labels:
                      - label1
                      - label2
                      name: BuilderRun1
                  - kind: parameter
                    name: Input1
                    parameter:
                      datatype: file
                      default: mydata.csv
                      optional: true
                    runnable:
                      kind: builder
                      labels:
                      - label1
                      - label2
                      name: BuilderRun1
                  kind: trainer
                  labels:
                  - trainer
                  name: MyTrainer
                  outputs:
                  - kind: model
                    metadata:
                      datatype: file
                      default: mydata.csv
                      optional: true
                    name: Output1
                    runnable:
                      kind: builder
                      labels:
                      - label1
                      - label2
                      name: BuilderRun1
                  - kind: model
                    metadata:
                      datatype: file
                      default: mydata.csv
                      optional: true
                    name: Output1
                    runnable:
                      kind: builder
                      labels:
                      - label1
                      - label2
                      name: BuilderRun1
                  - kind: model
                    metadata:
                      datatype: file
                      default: mydata.csv
                      optional: true
                    name: Output1
                    runnable:
                      kind: builder
                      labels:
                      - label1
                      - label2
                      name: BuilderRun1
              example:
              - created: "2021-04-09T06:17:25Z"
                id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
                image:
                  registryUrl: myregistry.io
                  repository: example/builder
                  tag: "1.0"
                inputs:
                - kind: parameter
                  name: Input1
                  parameter:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
                - kind: parameter
                  name: Input1
                  parameter:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
                - kind: parameter
                  name: Input1
                  parameter:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
                kind: trainer
                labels:
                - trainer
                name: MyTrainer
                outputs:
                - kind: model
                  metadata:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  name: Output1
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
                - kind: model
                  metadata:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  name: Output1
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
                - kind: model
                  metadata:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  name: Output1
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
              - created: "2021-04-09T06:17:25Z"
                id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
                image:
                  registryUrl: myregistry.io
                  repository: example/builder
                  tag: "1.0"
                inputs:
                - kind: parameter
                  name: Input1
                  parameter:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
                - kind: parameter
                  name: Input1
                  parameter:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
                - kind: parameter
                  name: Input1
                  parameter:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
                kind: trainer
                labels:
                - trainer
                name: MyTrainer
                outputs:
                - kind: model
                  metadata:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  name: Output1
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
                - kind: model
                  metadata:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  name: Output1
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
                - kind: model
                  metadata:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  name: Output1
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
              - created: "2021-04-09T06:17:25Z"
                id: 3F59C655-AFF8-EAB8-FA17-44E154EF0557
                image:
                  registryUrl: myregistry.io
                  repository: example/builder
                  tag: "1.0"
                inputs:
                - kind: parameter
                  name: Input1
                  parameter:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
                - kind: parameter
                  name: Input1
                  parameter:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
                - kind: parameter
                  name: Input1
                  parameter:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
                kind: trainer
                labels:
                - trainer
                name: MyTrainer
                outputs:
                - kind: model
                  metadata:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  name: Output1
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
                - kind: model
                  metadata:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  name: Output1
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
                - kind: model
                  metadata:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  name: Output1
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
        "404":
          description: Not Found response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
    post:
      tags:
      - runnable
      summary: register runnable
      description: Register a runnable with the FuseML runnable store.
      operationId: runnable#register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Runnable'
            example:
              created: "2021-04-09T06:17:25Z"
              id: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
              image:
                registryUrl: myregistry.io
                repository: example/builder
                tag: "1.0"
              inputs:
              - kind: parameter
                name: Input1
                parameter:
                  datatype: file
                  default: mydata.csv
                  optional: true
                runnable:
                  kind: builder
                  labels:
                  - label1
                  - label2
                  name: BuilderRun1
              - kind: parameter
                name: Input1
                parameter:
                  datatype: file
                  default: mydata.csv
                  optional: true
                runnable:
                  kind: builder
                  labels:
                  - label1
                  - label2
                  name: BuilderRun1
              kind: trainer
              labels:
              - trainer
              name: MyTrainer
              outputs:
              - kind: model
                metadata:
                  datatype: file
                  default: mydata.csv
                  optional: true
                name: Output1
                runnable:
                  kind: builder
                  labels:
                  - label1
                  - label2
                  name: BuilderRun1
              - kind: model
                metadata:
                  datatype: file
                  default: mydata.csv
                  optional: true
                name: Output1
                runnable:
                  kind: builder
                  labels:
                  - label1
                  - label2
                  name: BuilderRun1
      responses:
        "201":
          description: Created response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Runnable'
              example:
                created: "2021-04-09T06:17:25Z"
                id: E330131A-4516-F39A-1E98-7CBF64E7E788
                image:
                  registryUrl: myregistry.io
                  repository: example/builder
                  tag: "1.0"
                inputs:
                - kind: parameter
                  name: Input1
                  parameter:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
                - kind: parameter
                  name: Input1
                  parameter:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
                kind: trainer
                labels:
                - trainer
                name: MyTrainer
                outputs:
                - kind: model
                  metadata:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  name: Output1
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
                - kind: model
                  metadata:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  name: Output1
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
        "400":
          description: Bad Request response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
  /runnables/{runnableNameOrId}:
    get:
      tags:
      - runnable
      summary: get runnable
      description: Retrieve an Runnable from FuseML.
      operationId: runnable#get
      parameters:
      - name: runnableNameOrId
        in: path
        description: Runnable name or id
        required: true
        schema:
          type: string
          description: Runnable name or id
          example: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
        example: 288BFD74-D973-18B5-FAA5-29ADF4569AC7
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Runnable'
              example:
                created: "2021-04-09T06:17:25Z"
                id: FF1D889F-0741-6290-783B-66E606310D86
                image:
                  registryUrl: myregistry.io
                  repository: example/builder
                  tag: "1.0"
                inputs:
                - kind: parameter
                  name: Input1
                  parameter:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
                - kind: parameter
                  name: Input1
                  parameter:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
                - kind: parameter
                  name: Input1
                  parameter:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
                - kind: parameter
                  name: Input1
                  parameter:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
                kind: trainer
                labels:
                - trainer
                name: MyTrainer
                outputs:
                - kind: model
                  metadata:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  name: Output1
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
                - kind: model
                  metadata:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  name: Output1
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
                - kind: model
                  metadata:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  name: Output1
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
                - kind: model
                  metadata:
                    datatype: file
                    default: mydata.csv
                    optional: true
                  name: Output1
                  runnable:
                    kind: builder
                    labels:
                    - label1
                    - label2
                    name: BuilderRun1
        "400":
          description: Bad Request response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
        "404":
          description: Not Found response.
          content:
            application/vnd.goa.error:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                id: 3F1FKVRR
                message: Value of ID must be an integer
                name: bad_request
components:
  schemas:
    Codeset:
      type: object
      properties:
        description:
          type: string
          description: Codeset description
          example: My first MLFlow application with FuseML
        label:
          type: string
          description: Additional Codeset label that helps with identifying the type
          example: mlflow
        location:
          type: string
          description: Path to the code that should be registered as Codeset
          example: work/ml/mlflow-code
        name:
          type: string
          description: The name of the Codeset
          example: mlflow-app-01
        project:
          type: string
          description: The project this Codeset belongs to
          example: mlflow-project-01
      example:
        description: My first MLFlow application with FuseML
        label: mlflow
        location: work/ml/mlflow-code
        name: mlflow-app-01
        project: mlflow-project-01
      required:
      - name
      - project
      - location
    Error:
      type: object
      properties:
        fault:
          type: boolean
          description: Is the error a server-side fault?
          example: false
        id:
          type: string
          description: ID is a unique identifier for this particular occurrence of
            the problem.
          example: 123abc
        message:
          type: string
          description: Message is a human-readable explanation specific to this occurrence
            of the problem.
          example: parameter 'p' must be an integer
        name:
          type: string
          description: Name is the name of this class of errors.
          example: bad_request
        temporary:
          type: boolean
          description: Is the error temporary?
          example: true
        timeout:
          type: boolean
          description: Is the error a timeout?
          example: true
      description: If the Codeset is not found, should return 404 Not Found.
      example:
        id: 3F1FKVRR
        message: Value of ID must be an integer
        name: bad_request
      required:
      - name
      - id
      - message
      - temporary
      - timeout
      - fault
    InputParameter:
      type: object
      properties:
        datatype:
          type: string
          description: Parameter data type
          example: file
        default:
          type: string
          description: Default value
          example: mydata.csv
        optional:
          type: boolean
          description: Optional parameter
          example: true
      example:
        datatype: file
        default: mydata.csv
        optional: true
    Runnable:
      type: object
      properties:
        created:
          type: string
          description: The runnable's creation time
          example: "2021-04-09T06:17:25Z"
          format: date-time
        id:
          type: string
          description: The ID of the runnable
          example: AC77D914-0A36-9917-2BA7-F519556A50B8
          format: uuid
        image:
          $ref: '#/components/schemas/RunnableImage'
        inputs:
          type: array
          items:
            $ref: '#/components/schemas/RunnableInput'
          description: List of inputs (artifacts, values etc.) accepted by this runnable
          example:
          - kind: parameter
            name: Input1
            parameter:
              datatype: file
              default: mydata.csv
              optional: true
            runnable:
              kind: builder
              labels:
              - label1
              - label2
              name: BuilderRun1
          - kind: parameter
            name: Input1
            parameter:
              datatype: file
              default: mydata.csv
              optional: true
            runnable:
              kind: builder
              labels:
              - label1
              - label2
              name: BuilderRun1
          - kind: parameter
            name: Input1
            parameter:
              datatype: file
              default: mydata.csv
              optional: true
            runnable:
              kind: builder
              labels:
              - label1
              - label2
              name: BuilderRun1
        kind:
          type: string
          description: The kind of runnable (builder, trainer, predictor etc.)
          example: trainer
        labels:
          type: array
          items:
            type: string
            example: Iusto minus.
          description: Labels associated with the runnable
          example:
          - trainer
        name:
          type: string
          description: The name of the runnable
          example: MyTrainer
        outputs:
          type: array
          items:
            $ref: '#/components/schemas/RunnableOutput'
          description: List of outputs (artifacts, values etc.) generated by this
            runnable
          example:
          - kind: model
            metadata:
              datatype: file
              default: mydata.csv
              optional: true
            name: Output1
            runnable:
              kind: builder
              labels:
              - label1
              - label2
              name: BuilderRun1
          - kind: model
            metadata:
              datatype: file
              default: mydata.csv
              optional: true
            name: Output1
            runnable:
              kind: builder
              labels:
              - label1
              - label2
              name: BuilderRun1
          - kind: model
            metadata:
              datatype: file
              default: mydata.csv
              optional: true
            name: Output1
            runnable:
              kind: builder
              labels:
              - label1
              - label2
              name: BuilderRun1
      example:
        created: "2021-04-09T06:17:25Z"
        id: A129B534-C1FC-F09D-BF29-3DA5781E0ECB
        image:
          registryUrl: myregistry.io
          repository: example/builder
          tag: "1.0"
        inputs:
        - kind: parameter
          name: Input1
          parameter:
            datatype: file
            default: mydata.csv
            optional: true
          runnable:
            kind: builder
            labels:
            - label1
            - label2
            name: BuilderRun1
        - kind: parameter
          name: Input1
          parameter:
            datatype: file
            default: mydata.csv
            optional: true
          runnable:
            kind: builder
            labels:
            - label1
            - label2
            name: BuilderRun1
        kind: trainer
        labels:
        - trainer
        name: MyTrainer
        outputs:
        - kind: model
          metadata:
            datatype: file
            default: mydata.csv
            optional: true
          name: Output1
          runnable:
            kind: builder
            labels:
            - label1
            - label2
            name: BuilderRun1
        - kind: model
          metadata:
            datatype: file
            default: mydata.csv
            optional: true
          name: Output1
          runnable:
            kind: builder
            labels:
            - label1
            - label2
            name: BuilderRun1
        - kind: model
          metadata:
            datatype: file
            default: mydata.csv
            optional: true
          name: Output1
          runnable:
            kind: builder
            labels:
            - label1
            - label2
            name: BuilderRun1
        - kind: model
          metadata:
            datatype: file
            default: mydata.csv
            optional: true
          name: Output1
          runnable:
            kind: builder
            labels:
            - label1
            - label2
            name: BuilderRun1
      required:
      - name
      - kind
      - image
      - inputs
      - outputs
      - labels
    RunnableImage:
      type: object
      properties:
        registryUrl:
          type: string
          description: The URL for the external registry where the image is stored
            (empty for internal images)
          example: myregistry.io
        repository:
          type: string
          description: The image repository
          example: example/builder
        tag:
          type: string
          description: The image tag
          example: "1.0"
      example:
        registryUrl: myregistry.io
        repository: example/builder
        tag: "1.0"
    RunnableInput:
      type: object
      properties:
        kind:
          type: string
          description: Kind of input (e.g. runnable, dataset, model, parameter, etc.)
          example: parameter
        name:
          type: string
          description: Input name
          example: Input1
        parameter:
          $ref: '#/components/schemas/InputParameter'
        runnable:
          $ref: '#/components/schemas/RunnableRef'
      example:
        kind: parameter
        name: Input1
        parameter:
          datatype: file
          default: mydata.csv
          optional: true
        runnable:
          kind: builder
          labels:
          - label1
          - label2
          name: BuilderRun1
    RunnableOutput:
      type: object
      properties:
        kind:
          type: string
          description: Kind of output (e.g. runnable, dataset, model, metatada, etc.)
          example: model
        metadata:
          $ref: '#/components/schemas/InputParameter'
        name:
          type: string
          description: Output name
          example: Output1
        runnable:
          $ref: '#/components/schemas/RunnableRef'
      example:
        kind: model
        metadata:
          datatype: file
          default: mydata.csv
          optional: true
        name: Output1
        runnable:
          kind: builder
          labels:
          - label1
          - label2
          name: BuilderRun1
    RunnableRef:
      type: object
      properties:
        kind:
          type: string
          description: Runnable kind
          example: builder
        labels:
          type: array
          items:
            type: string
            example: Modi est.
          description: Runnable labels
          example:
          - label1
          - label2
        name:
          type: string
          description: Runnable name
          example: BuilderRun1
      example:
        kind: builder
        labels:
        - label1
        - label2
        name: BuilderRun1
