swagger: "2.0"
info:
  title: FuseML core API
  description: Provides an API for the core operations of FuseML
  version: ""
host: localhost:8000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /api/openapi.json:
    get:
      tags:
      - openapi
      summary: Download gen/http/openapi.json
      description: JSON document containing the API swagger definition
      operationId: openapi#/api/openapi.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
  /api/openapi.yaml:
    get:
      tags:
      - openapi
      summary: Download gen/http/openapi.yaml
      description: JSON document containing the API swagger definition
      operationId: openapi#/api/openapi.yaml
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
  /api/openapi3.json:
    get:
      tags:
      - openapi
      summary: Download gen/http/openapi3.json
      description: JSON document containing the API swagger definition
      operationId: openapi#/api/openapi3.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
  /api/openapi3.yaml:
    get:
      tags:
      - openapi
      summary: Download gen/http/openapi3.yaml
      description: JSON document containing the API swagger definition
      operationId: openapi#/api/openapi3.yaml
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
  /runnables:
    get:
      tags:
      - runnable
      summary: list runnable
      description: Retrieve information about runnables registered in FuseML.
      operationId: runnable#list
      parameters:
      - name: kind
        in: query
        description: Kind of a registered runnables
        required: false
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              $ref: '#/definitions/RunnableResponse'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/RunnableListNotFoundResponseBody'
      schemes:
      - http
    post:
      tags:
      - runnable
      summary: register runnable
      description: Register a runnable with the FuseML runnable store.
      operationId: runnable#register
      parameters:
      - name: RegisterRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/RunnableRegisterRequestBody'
          required:
          - name
          - kind
          - image
          - inputs
          - outputs
          - labels
      responses:
        "201":
          description: Created response.
          schema:
            $ref: '#/definitions/RunnableRegisterResponseBody'
            required:
            - name
            - kind
            - image
            - inputs
            - outputs
            - labels
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/RunnableRegisterBadRequestResponseBody'
      schemes:
      - http
  /runnables/{runnableNameOrId}:
    get:
      tags:
      - runnable
      summary: get runnable
      description: Retrieve an Runnable from FuseML.
      operationId: runnable#get
      parameters:
      - name: runnableNameOrId
        in: path
        description: Runnable name or id
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/RunnableGetResponseBody'
            required:
            - name
            - kind
            - image
            - inputs
            - outputs
            - labels
        "400":
          description: Bad Request response.
          schema:
            $ref: '#/definitions/RunnableGetBadRequestResponseBody'
        "404":
          description: Not Found response.
          schema:
            $ref: '#/definitions/RunnableGetNotFoundResponseBody'
      schemes:
      - http
definitions:
  InputParameterRequestBody:
    title: InputParameterRequestBody
    type: object
    properties:
      datatype:
        type: string
        description: Parameter data type
        example: Culpa ut.
      default:
        type: string
        description: Default value
        example: Placeat minus.
      optional:
        type: boolean
        description: Optional parameter
        example: false
    example:
      datatype: Sed pariatur asperiores fugiat accusantium aut suscipit.
      default: Non quia.
      optional: false
  InputParameterResponse:
    title: InputParameterResponse
    type: object
    properties:
      datatype:
        type: string
        description: Parameter data type
        example: Et ex.
      default:
        type: string
        description: Default value
        example: Magni et omnis harum dolorem.
      optional:
        type: boolean
        description: Optional parameter
        example: true
    example:
      datatype: Et non ullam maxime vel sapiente.
      default: Sit nihil animi error enim blanditiis.
      optional: true
  InputParameterResponseBody:
    title: InputParameterResponseBody
    type: object
    properties:
      datatype:
        type: string
        description: Parameter data type
        example: Iusto totam cumque ipsum.
      default:
        type: string
        description: Default value
        example: Consequatur eius laboriosam nam similique.
      optional:
        type: boolean
        description: Optional parameter
        example: false
    example:
      datatype: Doloribus sed deserunt reiciendis tempore non.
      default: Sequi eos quasi enim et.
      optional: true
  RunnableGetBadRequestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: If not name neither ID is given, should return 400 Bad Request. (default
      view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  RunnableGetNotFoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: If there is no runnable with the given name/id, should return 404
      Not Found. (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  RunnableGetResponseBody:
    title: RunnableGetResponseBody
    type: object
    properties:
      created:
        type: string
        description: The runnable's creation time
        example: "1993-08-26T11:36:16Z"
        format: date-time
      id:
        type: string
        description: The ID of the runnable
        example: D358BA94-28F1-C0F1-EA4E-E3BFBD8A6AE2
        format: uuid
      image:
        $ref: '#/definitions/RunnableImageResponseBody'
      inputs:
        type: array
        items:
          $ref: '#/definitions/RunnableInputResponseBody'
        description: List of inputs (artifacts, values etc.) accepted by this runnable
        example:
        - kind: Sed ut qui ipsum adipisci.
          name: Tenetur omnis.
          parameter:
            datatype: Doloribus enim qui harum facere.
            default: Eligendi veritatis excepturi quisquam quo a.
            optional: true
          runnable:
            kind: Enim nesciunt est.
            labels:
            - Vero corrupti.
            - Iure consequuntur.
            name: Laborum quos voluptatibus.
        - kind: Sed ut qui ipsum adipisci.
          name: Tenetur omnis.
          parameter:
            datatype: Doloribus enim qui harum facere.
            default: Eligendi veritatis excepturi quisquam quo a.
            optional: true
          runnable:
            kind: Enim nesciunt est.
            labels:
            - Vero corrupti.
            - Iure consequuntur.
            name: Laborum quos voluptatibus.
        - kind: Sed ut qui ipsum adipisci.
          name: Tenetur omnis.
          parameter:
            datatype: Doloribus enim qui harum facere.
            default: Eligendi veritatis excepturi quisquam quo a.
            optional: true
          runnable:
            kind: Enim nesciunt est.
            labels:
            - Vero corrupti.
            - Iure consequuntur.
            name: Laborum quos voluptatibus.
        - kind: Sed ut qui ipsum adipisci.
          name: Tenetur omnis.
          parameter:
            datatype: Doloribus enim qui harum facere.
            default: Eligendi veritatis excepturi quisquam quo a.
            optional: true
          runnable:
            kind: Enim nesciunt est.
            labels:
            - Vero corrupti.
            - Iure consequuntur.
            name: Laborum quos voluptatibus.
      kind:
        type: string
        description: The kind of runnable (builder, trainer, predictor etc.)
        example: Tenetur aliquam.
      labels:
        type: array
        items:
          type: string
          example: Ipsam aut soluta optio quo.
        description: Labels associated with the runnable
        example:
        - Cum iure dignissimos.
        - Sit sunt atque.
        - Dolore dolores fugiat quasi.
      name:
        type: string
        description: The name of the runnable
        example: Ducimus nesciunt.
      outputs:
        type: array
        items:
          $ref: '#/definitions/RunnableOutputResponseBody'
        description: List of outputs (artifacts, values etc.) generated by this runnable
        example:
        - kind: Ut eveniet dolor quos ducimus officiis.
          metadata:
            datatype: Doloribus enim qui harum facere.
            default: Eligendi veritatis excepturi quisquam quo a.
            optional: true
          name: Ipsa officiis necessitatibus.
          runnable:
            kind: Enim nesciunt est.
            labels:
            - Vero corrupti.
            - Iure consequuntur.
            name: Laborum quos voluptatibus.
        - kind: Ut eveniet dolor quos ducimus officiis.
          metadata:
            datatype: Doloribus enim qui harum facere.
            default: Eligendi veritatis excepturi quisquam quo a.
            optional: true
          name: Ipsa officiis necessitatibus.
          runnable:
            kind: Enim nesciunt est.
            labels:
            - Vero corrupti.
            - Iure consequuntur.
            name: Laborum quos voluptatibus.
        - kind: Ut eveniet dolor quos ducimus officiis.
          metadata:
            datatype: Doloribus enim qui harum facere.
            default: Eligendi veritatis excepturi quisquam quo a.
            optional: true
          name: Ipsa officiis necessitatibus.
          runnable:
            kind: Enim nesciunt est.
            labels:
            - Vero corrupti.
            - Iure consequuntur.
            name: Laborum quos voluptatibus.
        - kind: Ut eveniet dolor quos ducimus officiis.
          metadata:
            datatype: Doloribus enim qui harum facere.
            default: Eligendi veritatis excepturi quisquam quo a.
            optional: true
          name: Ipsa officiis necessitatibus.
          runnable:
            kind: Enim nesciunt est.
            labels:
            - Vero corrupti.
            - Iure consequuntur.
            name: Laborum quos voluptatibus.
    example:
      created: "1974-04-08T16:42:41Z"
      id: CEF3CAF7-AB82-083A-2F08-9497BE6B7488
      image:
        registryUrl: Aut quae quia quasi molestiae.
        repository: Laboriosam et error ut quam.
        tag: Nam sunt et voluptas ipsam neque id.
      inputs:
      - kind: Sed ut qui ipsum adipisci.
        name: Tenetur omnis.
        parameter:
          datatype: Doloribus enim qui harum facere.
          default: Eligendi veritatis excepturi quisquam quo a.
          optional: true
        runnable:
          kind: Enim nesciunt est.
          labels:
          - Vero corrupti.
          - Iure consequuntur.
          name: Laborum quos voluptatibus.
      - kind: Sed ut qui ipsum adipisci.
        name: Tenetur omnis.
        parameter:
          datatype: Doloribus enim qui harum facere.
          default: Eligendi veritatis excepturi quisquam quo a.
          optional: true
        runnable:
          kind: Enim nesciunt est.
          labels:
          - Vero corrupti.
          - Iure consequuntur.
          name: Laborum quos voluptatibus.
      - kind: Sed ut qui ipsum adipisci.
        name: Tenetur omnis.
        parameter:
          datatype: Doloribus enim qui harum facere.
          default: Eligendi veritatis excepturi quisquam quo a.
          optional: true
        runnable:
          kind: Enim nesciunt est.
          labels:
          - Vero corrupti.
          - Iure consequuntur.
          name: Laborum quos voluptatibus.
      kind: Sit voluptas nobis tempore.
      labels:
      - Ut atque.
      - Ut quia adipisci esse est.
      name: Eius eius doloremque modi autem.
      outputs:
      - kind: Ut eveniet dolor quos ducimus officiis.
        metadata:
          datatype: Doloribus enim qui harum facere.
          default: Eligendi veritatis excepturi quisquam quo a.
          optional: true
        name: Ipsa officiis necessitatibus.
        runnable:
          kind: Enim nesciunt est.
          labels:
          - Vero corrupti.
          - Iure consequuntur.
          name: Laborum quos voluptatibus.
      - kind: Ut eveniet dolor quos ducimus officiis.
        metadata:
          datatype: Doloribus enim qui harum facere.
          default: Eligendi veritatis excepturi quisquam quo a.
          optional: true
        name: Ipsa officiis necessitatibus.
        runnable:
          kind: Enim nesciunt est.
          labels:
          - Vero corrupti.
          - Iure consequuntur.
          name: Laborum quos voluptatibus.
      - kind: Ut eveniet dolor quos ducimus officiis.
        metadata:
          datatype: Doloribus enim qui harum facere.
          default: Eligendi veritatis excepturi quisquam quo a.
          optional: true
        name: Ipsa officiis necessitatibus.
        runnable:
          kind: Enim nesciunt est.
          labels:
          - Vero corrupti.
          - Iure consequuntur.
          name: Laborum quos voluptatibus.
    required:
    - name
    - kind
    - image
    - inputs
    - outputs
    - labels
  RunnableImageRequestBody:
    title: RunnableImageRequestBody
    type: object
    properties:
      registryUrl:
        type: string
        description: The URL for the external registry where the image is stored (empty
          for internal images)
        example: Eum tenetur.
      repository:
        type: string
        description: The image repository
        example: Commodi distinctio quaerat delectus tempore voluptatem.
      tag:
        type: string
        description: The image tag
        example: Suscipit ducimus harum voluptas totam.
    example:
      registryUrl: Corrupti et.
      repository: Labore debitis.
      tag: Voluptas aspernatur.
  RunnableImageResponse:
    title: RunnableImageResponse
    type: object
    properties:
      registryUrl:
        type: string
        description: The URL for the external registry where the image is stored (empty
          for internal images)
        example: Autem voluptatibus odit.
      repository:
        type: string
        description: The image repository
        example: Fuga labore impedit.
      tag:
        type: string
        description: The image tag
        example: Consequatur harum.
    example:
      registryUrl: Est omnis consequatur distinctio blanditiis.
      repository: Aliquam dolorem odit.
      tag: Quis velit.
  RunnableImageResponseBody:
    title: RunnableImageResponseBody
    type: object
    properties:
      registryUrl:
        type: string
        description: The URL for the external registry where the image is stored (empty
          for internal images)
        example: Assumenda est tempora non accusantium quia.
      repository:
        type: string
        description: The image repository
        example: Cum aperiam commodi quisquam fuga assumenda.
      tag:
        type: string
        description: The image tag
        example: Eligendi maiores in nam quia assumenda.
    example:
      registryUrl: Voluptatem cumque.
      repository: Perspiciatis eius accusantium magnam.
      tag: Aliquid voluptas sit nobis minus laborum optio.
  RunnableInputRequestBody:
    title: RunnableInputRequestBody
    type: object
    properties:
      kind:
        type: string
        description: Kind of input (e.g. runnable, dataset, model, parameter, etc.)
        example: Magnam corrupti quas non provident.
      name:
        type: string
        description: Input name
        example: Ut animi earum quo minus ea.
      parameter:
        $ref: '#/definitions/InputParameterRequestBody'
      runnable:
        $ref: '#/definitions/RunnableRefRequestBody'
    example:
      kind: Ea voluptate tempore.
      name: Tenetur ab sint labore.
      parameter:
        datatype: Debitis ut provident voluptatibus sit laudantium.
        default: Rem eum.
        optional: true
      runnable:
        kind: Et mollitia iste libero sapiente sint et.
        labels:
        - Dolor nulla aut voluptatibus qui nihil.
        - Placeat ipsum aut.
        - A enim tempora sapiente debitis sint ut.
        - Eligendi porro.
        name: Enim dolorum.
  RunnableInputResponse:
    title: RunnableInputResponse
    type: object
    properties:
      kind:
        type: string
        description: Kind of input (e.g. runnable, dataset, model, parameter, etc.)
        example: Dolor nam sint blanditiis harum.
      name:
        type: string
        description: Input name
        example: Quisquam deserunt.
      parameter:
        $ref: '#/definitions/InputParameterResponse'
      runnable:
        $ref: '#/definitions/RunnableRefResponse'
    example:
      kind: Ea eaque fuga id.
      name: Sit nesciunt nulla.
      parameter:
        datatype: Molestias accusantium aspernatur totam animi.
        default: Natus accusantium qui nostrum et officiis earum.
        optional: false
      runnable:
        kind: Debitis distinctio magni quisquam aut temporibus vel.
        labels:
        - Facere dolore eius.
        - Maxime et.
        name: Laudantium fugit autem ipsa voluptas ut commodi.
  RunnableInputResponseBody:
    title: RunnableInputResponseBody
    type: object
    properties:
      kind:
        type: string
        description: Kind of input (e.g. runnable, dataset, model, parameter, etc.)
        example: Officia minima quos debitis a.
      name:
        type: string
        description: Input name
        example: Quas aspernatur et.
      parameter:
        $ref: '#/definitions/InputParameterResponseBody'
      runnable:
        $ref: '#/definitions/RunnableRefResponseBody'
    example:
      kind: Quo illo necessitatibus qui.
      name: Praesentium ea ex enim quod facere.
      parameter:
        datatype: Doloribus enim qui harum facere.
        default: Eligendi veritatis excepturi quisquam quo a.
        optional: true
      runnable:
        kind: Enim nesciunt est.
        labels:
        - Vero corrupti.
        - Iure consequuntur.
        name: Laborum quos voluptatibus.
  RunnableListNotFoundResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: If the runnable is not found, should return 404 Not Found. (default
      view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  RunnableOutputRequestBody:
    title: RunnableOutputRequestBody
    type: object
    properties:
      kind:
        type: string
        description: Kind of output (e.g. runnable, dataset, model, metatada, etc.)
        example: Nisi totam magni consequatur.
      metadata:
        $ref: '#/definitions/InputParameterRequestBody'
      name:
        type: string
        description: Output name
        example: Consequatur dolores officiis.
      runnable:
        $ref: '#/definitions/RunnableRefRequestBody'
    example:
      kind: Aspernatur consequatur aut qui est commodi voluptatum.
      metadata:
        datatype: Debitis ut provident voluptatibus sit laudantium.
        default: Rem eum.
        optional: true
      name: Similique voluptatem quo repellendus consequuntur repellendus.
      runnable:
        kind: Et mollitia iste libero sapiente sint et.
        labels:
        - Dolor nulla aut voluptatibus qui nihil.
        - Placeat ipsum aut.
        - A enim tempora sapiente debitis sint ut.
        - Eligendi porro.
        name: Enim dolorum.
  RunnableOutputResponse:
    title: RunnableOutputResponse
    type: object
    properties:
      kind:
        type: string
        description: Kind of output (e.g. runnable, dataset, model, metatada, etc.)
        example: Et repellendus illum.
      metadata:
        $ref: '#/definitions/InputParameterResponse'
      name:
        type: string
        description: Output name
        example: Aut non quam est.
      runnable:
        $ref: '#/definitions/RunnableRefResponse'
    example:
      kind: Placeat voluptatem sit.
      metadata:
        datatype: Molestias accusantium aspernatur totam animi.
        default: Natus accusantium qui nostrum et officiis earum.
        optional: false
      name: Ab possimus.
      runnable:
        kind: Debitis distinctio magni quisquam aut temporibus vel.
        labels:
        - Facere dolore eius.
        - Maxime et.
        name: Laudantium fugit autem ipsa voluptas ut commodi.
  RunnableOutputResponseBody:
    title: RunnableOutputResponseBody
    type: object
    properties:
      kind:
        type: string
        description: Kind of output (e.g. runnable, dataset, model, metatada, etc.)
        example: Qui suscipit itaque.
      metadata:
        $ref: '#/definitions/InputParameterResponseBody'
      name:
        type: string
        description: Output name
        example: Repellat omnis ut omnis neque.
      runnable:
        $ref: '#/definitions/RunnableRefResponseBody'
    example:
      kind: Quasi illum reiciendis consectetur.
      metadata:
        datatype: Doloribus enim qui harum facere.
        default: Eligendi veritatis excepturi quisquam quo a.
        optional: true
      name: Dolore impedit quia possimus aspernatur aut.
      runnable:
        kind: Enim nesciunt est.
        labels:
        - Vero corrupti.
        - Iure consequuntur.
        name: Laborum quos voluptatibus.
  RunnableRefRequestBody:
    title: RunnableRefRequestBody
    type: object
    properties:
      kind:
        type: string
        description: Runnable kind
        example: Nemo consequuntur magni rem excepturi.
      labels:
        type: array
        items:
          type: string
          example: Et facilis nisi qui laudantium.
        description: Runnable labels
        example:
        - Labore aut et.
        - Dolorum exercitationem eligendi suscipit pariatur modi.
      name:
        type: string
        description: Runnable name
        example: Neque est quos aut temporibus debitis omnis.
    example:
      kind: Quis praesentium repellendus dolor asperiores ratione.
      labels:
      - Accusantium autem asperiores enim nobis quasi.
      - Magni reiciendis quia.
      - Deleniti laborum aut itaque rerum ab alias.
      - Pariatur quo.
      name: Voluptas aperiam voluptates qui.
  RunnableRefResponse:
    title: RunnableRefResponse
    type: object
    properties:
      kind:
        type: string
        description: Runnable kind
        example: Similique suscipit inventore magnam natus architecto amet.
      labels:
        type: array
        items:
          type: string
          example: Molestiae culpa iste est velit qui nulla.
        description: Runnable labels
        example:
        - Rerum est ipsum dolor modi.
        - Quo maiores ut ab dolorem voluptatem.
        - Nihil quia nulla sequi quia molestiae in.
        - Necessitatibus dolores architecto totam in ad itaque.
      name:
        type: string
        description: Runnable name
        example: Doloremque molestias id totam quis qui.
    example:
      kind: In quod corporis suscipit similique qui.
      labels:
      - Alias at et et voluptas.
      - Odio eligendi voluptas ut officiis cumque.
      name: Consectetur cupiditate non molestias quidem omnis.
  RunnableRefResponseBody:
    title: RunnableRefResponseBody
    type: object
    properties:
      kind:
        type: string
        description: Runnable kind
        example: Qui ea dolores.
      labels:
        type: array
        items:
          type: string
          example: Beatae necessitatibus voluptas animi.
        description: Runnable labels
        example:
        - Et temporibus repudiandae magni temporibus.
        - Assumenda cumque.
        - Qui quas.
        - Ea porro fugit iusto velit.
      name:
        type: string
        description: Runnable name
        example: Necessitatibus deleniti non provident consequatur cupiditate.
    example:
      kind: Et nam excepturi non non eius.
      labels:
      - Consequatur incidunt et odio et suscipit.
      - Qui perspiciatis nisi unde at dolor.
      - Eos dignissimos magnam placeat quis et eius.
      - Vitae recusandae assumenda.
      name: Est harum nisi.
  RunnableRegisterBadRequestResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: true
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: If the runnable does not have the required fields, should return
      400 Bad Request. (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  RunnableRegisterRequestBody:
    title: RunnableRegisterRequestBody
    type: object
    properties:
      created:
        type: string
        description: The runnable's creation time
        example: "2010-03-25T19:10:03Z"
        format: date-time
      id:
        type: string
        description: The ID of the runnable
        example: 233374F1-297F-8711-5FC3-4F6B3731AD63
        format: uuid
      image:
        $ref: '#/definitions/RunnableImageRequestBody'
      inputs:
        type: array
        items:
          $ref: '#/definitions/RunnableInputRequestBody'
        description: List of inputs (artifacts, values etc.) accepted by this runnable
        example:
        - kind: Minus aut.
          name: Incidunt vitae illum eveniet.
          parameter:
            datatype: Debitis ut provident voluptatibus sit laudantium.
            default: Rem eum.
            optional: true
          runnable:
            kind: Et mollitia iste libero sapiente sint et.
            labels:
            - Dolor nulla aut voluptatibus qui nihil.
            - Placeat ipsum aut.
            - A enim tempora sapiente debitis sint ut.
            - Eligendi porro.
            name: Enim dolorum.
        - kind: Minus aut.
          name: Incidunt vitae illum eveniet.
          parameter:
            datatype: Debitis ut provident voluptatibus sit laudantium.
            default: Rem eum.
            optional: true
          runnable:
            kind: Et mollitia iste libero sapiente sint et.
            labels:
            - Dolor nulla aut voluptatibus qui nihil.
            - Placeat ipsum aut.
            - A enim tempora sapiente debitis sint ut.
            - Eligendi porro.
            name: Enim dolorum.
        - kind: Minus aut.
          name: Incidunt vitae illum eveniet.
          parameter:
            datatype: Debitis ut provident voluptatibus sit laudantium.
            default: Rem eum.
            optional: true
          runnable:
            kind: Et mollitia iste libero sapiente sint et.
            labels:
            - Dolor nulla aut voluptatibus qui nihil.
            - Placeat ipsum aut.
            - A enim tempora sapiente debitis sint ut.
            - Eligendi porro.
            name: Enim dolorum.
      kind:
        type: string
        description: The kind of runnable (builder, trainer, predictor etc.)
        example: Beatae est.
      labels:
        type: array
        items:
          type: string
          example: Velit harum aut ut ad.
        description: Labels associated with the runnable
        example:
        - Optio commodi odio nemo dolorem in.
        - Et ex ea aut.
        - Voluptas pariatur officiis optio.
        - Deserunt vel rerum delectus velit modi voluptatem.
      name:
        type: string
        description: The name of the runnable
        example: Aut recusandae voluptatem porro odio quis.
      outputs:
        type: array
        items:
          $ref: '#/definitions/RunnableOutputRequestBody'
        description: List of outputs (artifacts, values etc.) generated by this runnable
        example:
        - kind: Et similique suscipit laborum porro praesentium.
          metadata:
            datatype: Debitis ut provident voluptatibus sit laudantium.
            default: Rem eum.
            optional: true
          name: Atque blanditiis libero minima.
          runnable:
            kind: Et mollitia iste libero sapiente sint et.
            labels:
            - Dolor nulla aut voluptatibus qui nihil.
            - Placeat ipsum aut.
            - A enim tempora sapiente debitis sint ut.
            - Eligendi porro.
            name: Enim dolorum.
        - kind: Et similique suscipit laborum porro praesentium.
          metadata:
            datatype: Debitis ut provident voluptatibus sit laudantium.
            default: Rem eum.
            optional: true
          name: Atque blanditiis libero minima.
          runnable:
            kind: Et mollitia iste libero sapiente sint et.
            labels:
            - Dolor nulla aut voluptatibus qui nihil.
            - Placeat ipsum aut.
            - A enim tempora sapiente debitis sint ut.
            - Eligendi porro.
            name: Enim dolorum.
        - kind: Et similique suscipit laborum porro praesentium.
          metadata:
            datatype: Debitis ut provident voluptatibus sit laudantium.
            default: Rem eum.
            optional: true
          name: Atque blanditiis libero minima.
          runnable:
            kind: Et mollitia iste libero sapiente sint et.
            labels:
            - Dolor nulla aut voluptatibus qui nihil.
            - Placeat ipsum aut.
            - A enim tempora sapiente debitis sint ut.
            - Eligendi porro.
            name: Enim dolorum.
    description: Runnable descriptor
    example:
      created: "1978-02-24T10:49:05Z"
      id: 1576BB1F-D21C-05AD-6677-73725A387FA6
      image:
        registryUrl: Quidem hic sapiente quasi quia explicabo.
        repository: Et esse.
        tag: Consectetur ex doloribus qui.
      inputs:
      - kind: Minus aut.
        name: Incidunt vitae illum eveniet.
        parameter:
          datatype: Debitis ut provident voluptatibus sit laudantium.
          default: Rem eum.
          optional: true
        runnable:
          kind: Et mollitia iste libero sapiente sint et.
          labels:
          - Dolor nulla aut voluptatibus qui nihil.
          - Placeat ipsum aut.
          - A enim tempora sapiente debitis sint ut.
          - Eligendi porro.
          name: Enim dolorum.
      - kind: Minus aut.
        name: Incidunt vitae illum eveniet.
        parameter:
          datatype: Debitis ut provident voluptatibus sit laudantium.
          default: Rem eum.
          optional: true
        runnable:
          kind: Et mollitia iste libero sapiente sint et.
          labels:
          - Dolor nulla aut voluptatibus qui nihil.
          - Placeat ipsum aut.
          - A enim tempora sapiente debitis sint ut.
          - Eligendi porro.
          name: Enim dolorum.
      - kind: Minus aut.
        name: Incidunt vitae illum eveniet.
        parameter:
          datatype: Debitis ut provident voluptatibus sit laudantium.
          default: Rem eum.
          optional: true
        runnable:
          kind: Et mollitia iste libero sapiente sint et.
          labels:
          - Dolor nulla aut voluptatibus qui nihil.
          - Placeat ipsum aut.
          - A enim tempora sapiente debitis sint ut.
          - Eligendi porro.
          name: Enim dolorum.
      - kind: Minus aut.
        name: Incidunt vitae illum eveniet.
        parameter:
          datatype: Debitis ut provident voluptatibus sit laudantium.
          default: Rem eum.
          optional: true
        runnable:
          kind: Et mollitia iste libero sapiente sint et.
          labels:
          - Dolor nulla aut voluptatibus qui nihil.
          - Placeat ipsum aut.
          - A enim tempora sapiente debitis sint ut.
          - Eligendi porro.
          name: Enim dolorum.
      kind: Asperiores omnis eveniet minus velit.
      labels:
      - Omnis quis sed sapiente.
      - Ut placeat.
      - Voluptatem sit modi omnis dolor.
      - Voluptatem cumque corporis.
      name: Tenetur corporis ut illum.
      outputs:
      - kind: Et similique suscipit laborum porro praesentium.
        metadata:
          datatype: Debitis ut provident voluptatibus sit laudantium.
          default: Rem eum.
          optional: true
        name: Atque blanditiis libero minima.
        runnable:
          kind: Et mollitia iste libero sapiente sint et.
          labels:
          - Dolor nulla aut voluptatibus qui nihil.
          - Placeat ipsum aut.
          - A enim tempora sapiente debitis sint ut.
          - Eligendi porro.
          name: Enim dolorum.
      - kind: Et similique suscipit laborum porro praesentium.
        metadata:
          datatype: Debitis ut provident voluptatibus sit laudantium.
          default: Rem eum.
          optional: true
        name: Atque blanditiis libero minima.
        runnable:
          kind: Et mollitia iste libero sapiente sint et.
          labels:
          - Dolor nulla aut voluptatibus qui nihil.
          - Placeat ipsum aut.
          - A enim tempora sapiente debitis sint ut.
          - Eligendi porro.
          name: Enim dolorum.
      - kind: Et similique suscipit laborum porro praesentium.
        metadata:
          datatype: Debitis ut provident voluptatibus sit laudantium.
          default: Rem eum.
          optional: true
        name: Atque blanditiis libero minima.
        runnable:
          kind: Et mollitia iste libero sapiente sint et.
          labels:
          - Dolor nulla aut voluptatibus qui nihil.
          - Placeat ipsum aut.
          - A enim tempora sapiente debitis sint ut.
          - Eligendi porro.
          name: Enim dolorum.
      - kind: Et similique suscipit laborum porro praesentium.
        metadata:
          datatype: Debitis ut provident voluptatibus sit laudantium.
          default: Rem eum.
          optional: true
        name: Atque blanditiis libero minima.
        runnable:
          kind: Et mollitia iste libero sapiente sint et.
          labels:
          - Dolor nulla aut voluptatibus qui nihil.
          - Placeat ipsum aut.
          - A enim tempora sapiente debitis sint ut.
          - Eligendi porro.
          name: Enim dolorum.
    required:
    - name
    - kind
    - image
    - inputs
    - outputs
    - labels
  RunnableRegisterResponseBody:
    title: RunnableRegisterResponseBody
    type: object
    properties:
      created:
        type: string
        description: The runnable's creation time
        example: "1993-10-13T23:11:13Z"
        format: date-time
      id:
        type: string
        description: The ID of the runnable
        example: AB12B85B-1864-53B4-4A92-3519B45D0D5E
        format: uuid
      image:
        $ref: '#/definitions/RunnableImageResponseBody'
      inputs:
        type: array
        items:
          $ref: '#/definitions/RunnableInputResponseBody'
        description: List of inputs (artifacts, values etc.) accepted by this runnable
        example:
        - kind: Sed ut qui ipsum adipisci.
          name: Tenetur omnis.
          parameter:
            datatype: Doloribus enim qui harum facere.
            default: Eligendi veritatis excepturi quisquam quo a.
            optional: true
          runnable:
            kind: Enim nesciunt est.
            labels:
            - Vero corrupti.
            - Iure consequuntur.
            name: Laborum quos voluptatibus.
        - kind: Sed ut qui ipsum adipisci.
          name: Tenetur omnis.
          parameter:
            datatype: Doloribus enim qui harum facere.
            default: Eligendi veritatis excepturi quisquam quo a.
            optional: true
          runnable:
            kind: Enim nesciunt est.
            labels:
            - Vero corrupti.
            - Iure consequuntur.
            name: Laborum quos voluptatibus.
        - kind: Sed ut qui ipsum adipisci.
          name: Tenetur omnis.
          parameter:
            datatype: Doloribus enim qui harum facere.
            default: Eligendi veritatis excepturi quisquam quo a.
            optional: true
          runnable:
            kind: Enim nesciunt est.
            labels:
            - Vero corrupti.
            - Iure consequuntur.
            name: Laborum quos voluptatibus.
      kind:
        type: string
        description: The kind of runnable (builder, trainer, predictor etc.)
        example: Adipisci fugit ea et.
      labels:
        type: array
        items:
          type: string
          example: Nihil praesentium sint tempore doloribus et iste.
        description: Labels associated with the runnable
        example:
        - Reprehenderit sed.
        - Distinctio voluptate praesentium.
      name:
        type: string
        description: The name of the runnable
        example: Dignissimos voluptatum non rerum voluptate aperiam dolor.
      outputs:
        type: array
        items:
          $ref: '#/definitions/RunnableOutputResponseBody'
        description: List of outputs (artifacts, values etc.) generated by this runnable
        example:
        - kind: Ut eveniet dolor quos ducimus officiis.
          metadata:
            datatype: Doloribus enim qui harum facere.
            default: Eligendi veritatis excepturi quisquam quo a.
            optional: true
          name: Ipsa officiis necessitatibus.
          runnable:
            kind: Enim nesciunt est.
            labels:
            - Vero corrupti.
            - Iure consequuntur.
            name: Laborum quos voluptatibus.
        - kind: Ut eveniet dolor quos ducimus officiis.
          metadata:
            datatype: Doloribus enim qui harum facere.
            default: Eligendi veritatis excepturi quisquam quo a.
            optional: true
          name: Ipsa officiis necessitatibus.
          runnable:
            kind: Enim nesciunt est.
            labels:
            - Vero corrupti.
            - Iure consequuntur.
            name: Laborum quos voluptatibus.
    example:
      created: "1985-08-20T20:50:35Z"
      id: 77DFBD55-EC3C-CF64-7021-5A80D932517B
      image:
        registryUrl: Aut quae quia quasi molestiae.
        repository: Laboriosam et error ut quam.
        tag: Nam sunt et voluptas ipsam neque id.
      inputs:
      - kind: Sed ut qui ipsum adipisci.
        name: Tenetur omnis.
        parameter:
          datatype: Doloribus enim qui harum facere.
          default: Eligendi veritatis excepturi quisquam quo a.
          optional: true
        runnable:
          kind: Enim nesciunt est.
          labels:
          - Vero corrupti.
          - Iure consequuntur.
          name: Laborum quos voluptatibus.
      - kind: Sed ut qui ipsum adipisci.
        name: Tenetur omnis.
        parameter:
          datatype: Doloribus enim qui harum facere.
          default: Eligendi veritatis excepturi quisquam quo a.
          optional: true
        runnable:
          kind: Enim nesciunt est.
          labels:
          - Vero corrupti.
          - Iure consequuntur.
          name: Laborum quos voluptatibus.
      - kind: Sed ut qui ipsum adipisci.
        name: Tenetur omnis.
        parameter:
          datatype: Doloribus enim qui harum facere.
          default: Eligendi veritatis excepturi quisquam quo a.
          optional: true
        runnable:
          kind: Enim nesciunt est.
          labels:
          - Vero corrupti.
          - Iure consequuntur.
          name: Laborum quos voluptatibus.
      - kind: Sed ut qui ipsum adipisci.
        name: Tenetur omnis.
        parameter:
          datatype: Doloribus enim qui harum facere.
          default: Eligendi veritatis excepturi quisquam quo a.
          optional: true
        runnable:
          kind: Enim nesciunt est.
          labels:
          - Vero corrupti.
          - Iure consequuntur.
          name: Laborum quos voluptatibus.
      kind: Labore qui facilis suscipit sit nihil dolorem.
      labels:
      - Voluptatem velit soluta eum itaque.
      - Et non culpa dolore.
      name: Ea et.
      outputs:
      - kind: Ut eveniet dolor quos ducimus officiis.
        metadata:
          datatype: Doloribus enim qui harum facere.
          default: Eligendi veritatis excepturi quisquam quo a.
          optional: true
        name: Ipsa officiis necessitatibus.
        runnable:
          kind: Enim nesciunt est.
          labels:
          - Vero corrupti.
          - Iure consequuntur.
          name: Laborum quos voluptatibus.
      - kind: Ut eveniet dolor quos ducimus officiis.
        metadata:
          datatype: Doloribus enim qui harum facere.
          default: Eligendi veritatis excepturi quisquam quo a.
          optional: true
        name: Ipsa officiis necessitatibus.
        runnable:
          kind: Enim nesciunt est.
          labels:
          - Vero corrupti.
          - Iure consequuntur.
          name: Laborum quos voluptatibus.
      - kind: Ut eveniet dolor quos ducimus officiis.
        metadata:
          datatype: Doloribus enim qui harum facere.
          default: Eligendi veritatis excepturi quisquam quo a.
          optional: true
        name: Ipsa officiis necessitatibus.
        runnable:
          kind: Enim nesciunt est.
          labels:
          - Vero corrupti.
          - Iure consequuntur.
          name: Laborum quos voluptatibus.
      - kind: Ut eveniet dolor quos ducimus officiis.
        metadata:
          datatype: Doloribus enim qui harum facere.
          default: Eligendi veritatis excepturi quisquam quo a.
          optional: true
        name: Ipsa officiis necessitatibus.
        runnable:
          kind: Enim nesciunt est.
          labels:
          - Vero corrupti.
          - Iure consequuntur.
          name: Laborum quos voluptatibus.
    required:
    - name
    - kind
    - image
    - inputs
    - outputs
    - labels
  RunnableResponse:
    title: RunnableResponse
    type: object
    properties:
      created:
        type: string
        description: The runnable's creation time
        example: "1973-08-28T11:49:15Z"
        format: date-time
      id:
        type: string
        description: The ID of the runnable
        example: AC77D914-0A36-9917-2BA7-F519556A50B8
        format: uuid
      image:
        $ref: '#/definitions/RunnableImageResponse'
      inputs:
        type: array
        items:
          $ref: '#/definitions/RunnableInputResponse'
        description: List of inputs (artifacts, values etc.) accepted by this runnable
        example:
        - kind: Et qui corrupti aliquid voluptatem architecto.
          name: Necessitatibus cupiditate voluptatem amet neque.
          parameter:
            datatype: Molestias accusantium aspernatur totam animi.
            default: Natus accusantium qui nostrum et officiis earum.
            optional: false
          runnable:
            kind: Debitis distinctio magni quisquam aut temporibus vel.
            labels:
            - Facere dolore eius.
            - Maxime et.
            name: Laudantium fugit autem ipsa voluptas ut commodi.
        - kind: Et qui corrupti aliquid voluptatem architecto.
          name: Necessitatibus cupiditate voluptatem amet neque.
          parameter:
            datatype: Molestias accusantium aspernatur totam animi.
            default: Natus accusantium qui nostrum et officiis earum.
            optional: false
          runnable:
            kind: Debitis distinctio magni quisquam aut temporibus vel.
            labels:
            - Facere dolore eius.
            - Maxime et.
            name: Laudantium fugit autem ipsa voluptas ut commodi.
        - kind: Et qui corrupti aliquid voluptatem architecto.
          name: Necessitatibus cupiditate voluptatem amet neque.
          parameter:
            datatype: Molestias accusantium aspernatur totam animi.
            default: Natus accusantium qui nostrum et officiis earum.
            optional: false
          runnable:
            kind: Debitis distinctio magni quisquam aut temporibus vel.
            labels:
            - Facere dolore eius.
            - Maxime et.
            name: Laudantium fugit autem ipsa voluptas ut commodi.
        - kind: Et qui corrupti aliquid voluptatem architecto.
          name: Necessitatibus cupiditate voluptatem amet neque.
          parameter:
            datatype: Molestias accusantium aspernatur totam animi.
            default: Natus accusantium qui nostrum et officiis earum.
            optional: false
          runnable:
            kind: Debitis distinctio magni quisquam aut temporibus vel.
            labels:
            - Facere dolore eius.
            - Maxime et.
            name: Laudantium fugit autem ipsa voluptas ut commodi.
      kind:
        type: string
        description: The kind of runnable (builder, trainer, predictor etc.)
        example: Illum dicta eaque iste est.
      labels:
        type: array
        items:
          type: string
          example: Soluta nam dolores consequatur.
        description: Labels associated with the runnable
        example:
        - Architecto et unde.
        - Aut impedit.
        - Modi in modi eligendi.
      name:
        type: string
        description: The name of the runnable
        example: Et nobis et omnis doloremque repudiandae vitae.
      outputs:
        type: array
        items:
          $ref: '#/definitions/RunnableOutputResponse'
        description: List of outputs (artifacts, values etc.) generated by this runnable
        example:
        - kind: Aut possimus qui libero omnis.
          metadata:
            datatype: Molestias accusantium aspernatur totam animi.
            default: Natus accusantium qui nostrum et officiis earum.
            optional: false
          name: Nisi nisi quis quas.
          runnable:
            kind: Debitis distinctio magni quisquam aut temporibus vel.
            labels:
            - Facere dolore eius.
            - Maxime et.
            name: Laudantium fugit autem ipsa voluptas ut commodi.
        - kind: Aut possimus qui libero omnis.
          metadata:
            datatype: Molestias accusantium aspernatur totam animi.
            default: Natus accusantium qui nostrum et officiis earum.
            optional: false
          name: Nisi nisi quis quas.
          runnable:
            kind: Debitis distinctio magni quisquam aut temporibus vel.
            labels:
            - Facere dolore eius.
            - Maxime et.
            name: Laudantium fugit autem ipsa voluptas ut commodi.
        - kind: Aut possimus qui libero omnis.
          metadata:
            datatype: Molestias accusantium aspernatur totam animi.
            default: Natus accusantium qui nostrum et officiis earum.
            optional: false
          name: Nisi nisi quis quas.
          runnable:
            kind: Debitis distinctio magni quisquam aut temporibus vel.
            labels:
            - Facere dolore eius.
            - Maxime et.
            name: Laudantium fugit autem ipsa voluptas ut commodi.
    example:
      created: "1995-05-03T07:10:53Z"
      id: 4CCDE767-7648-444F-D09F-4B4FFE4EB36B
      image:
        registryUrl: Sit commodi labore vel voluptatum inventore.
        repository: Fugit omnis quo distinctio blanditiis explicabo.
        tag: Neque dolorem ullam deserunt excepturi ut.
      inputs:
      - kind: Et qui corrupti aliquid voluptatem architecto.
        name: Necessitatibus cupiditate voluptatem amet neque.
        parameter:
          datatype: Molestias accusantium aspernatur totam animi.
          default: Natus accusantium qui nostrum et officiis earum.
          optional: false
        runnable:
          kind: Debitis distinctio magni quisquam aut temporibus vel.
          labels:
          - Facere dolore eius.
          - Maxime et.
          name: Laudantium fugit autem ipsa voluptas ut commodi.
      - kind: Et qui corrupti aliquid voluptatem architecto.
        name: Necessitatibus cupiditate voluptatem amet neque.
        parameter:
          datatype: Molestias accusantium aspernatur totam animi.
          default: Natus accusantium qui nostrum et officiis earum.
          optional: false
        runnable:
          kind: Debitis distinctio magni quisquam aut temporibus vel.
          labels:
          - Facere dolore eius.
          - Maxime et.
          name: Laudantium fugit autem ipsa voluptas ut commodi.
      - kind: Et qui corrupti aliquid voluptatem architecto.
        name: Necessitatibus cupiditate voluptatem amet neque.
        parameter:
          datatype: Molestias accusantium aspernatur totam animi.
          default: Natus accusantium qui nostrum et officiis earum.
          optional: false
        runnable:
          kind: Debitis distinctio magni quisquam aut temporibus vel.
          labels:
          - Facere dolore eius.
          - Maxime et.
          name: Laudantium fugit autem ipsa voluptas ut commodi.
      - kind: Et qui corrupti aliquid voluptatem architecto.
        name: Necessitatibus cupiditate voluptatem amet neque.
        parameter:
          datatype: Molestias accusantium aspernatur totam animi.
          default: Natus accusantium qui nostrum et officiis earum.
          optional: false
        runnable:
          kind: Debitis distinctio magni quisquam aut temporibus vel.
          labels:
          - Facere dolore eius.
          - Maxime et.
          name: Laudantium fugit autem ipsa voluptas ut commodi.
      kind: Ut recusandae officia harum est est et.
      labels:
      - Natus fuga ea.
      - Ex enim dolorum magni a dolor quasi.
      - Et nihil nisi.
      name: Non nesciunt debitis non.
      outputs:
      - kind: Aut possimus qui libero omnis.
        metadata:
          datatype: Molestias accusantium aspernatur totam animi.
          default: Natus accusantium qui nostrum et officiis earum.
          optional: false
        name: Nisi nisi quis quas.
        runnable:
          kind: Debitis distinctio magni quisquam aut temporibus vel.
          labels:
          - Facere dolore eius.
          - Maxime et.
          name: Laudantium fugit autem ipsa voluptas ut commodi.
      - kind: Aut possimus qui libero omnis.
        metadata:
          datatype: Molestias accusantium aspernatur totam animi.
          default: Natus accusantium qui nostrum et officiis earum.
          optional: false
        name: Nisi nisi quis quas.
        runnable:
          kind: Debitis distinctio magni quisquam aut temporibus vel.
          labels:
          - Facere dolore eius.
          - Maxime et.
          name: Laudantium fugit autem ipsa voluptas ut commodi.
    required:
    - name
    - kind
    - image
    - inputs
    - outputs
    - labels
